### PR TITLE
Logo integrated into sidebar and page topper

### PR DESCRIPTION
**Pull request by emprice**
Happy to make additional edits as needed. For now, the logo appears at the top of the page, at the top of the sidebar (which sticks as you scroll, so the logo will always be in view in at least one place), and the favicon (tiny icon in the browser tab). Minor adjustments were made to the logo to increase readability, particularly in dark mode.

### CODE REVIEW

**Comment by alfa33333** [comment]
I looked at the changes and put the logo as designed in the side bar to show the idea and why it should be displayed normally. The banner section is the one that should be discussed, though. For example,
image

**Comment by emprice** [comment]
I defer to @joshspeagle on this --- it's your website, I'm just doing some of the web coding. For the banner, I think it's easier to see the overlapping text when the logo is fainter and has no background. The sidebar doesn't have the same constraint.

**Comment by joshspeagle** [comment]
Agh, I missed this last week! I'm happy with the logo on the main banner as proposed and the sidebar as Tony suggested.

**Comment by joshspeagle** [comment]
Should we do THE MERGE?!

**Comment by emprice** [comment]
I'll incorporate the sidebar change and then it should be good to go! Will comment again when it's ready

**Comment by emprice** [comment]
@joshspeagle and/or @alfa33333, please check the current version (screenshots below). Happy to also mess with colors if these aren't to your liking. In general, I'm trying to keep sufficient contrast in dark mode so the logo is still easily read.

dark mode
light mode

**Comment by alfa33333** [comment]
I added a line of code so the light theme in the navigation has the specific colour  of the logo, but changes for the  dark theme. 
image
image

**Comment by emprice** [comment]
@alfa33333, there's a better way to implement that change in Sass, but I see what you want to do. I can push a commit later that does this. If the two logos are different colors in light theme, it makes sense to do something similar in dark theme as well. I'll propose something with sufficient contrast in my next commit.

**Comment by emprice** [comment]
Please review these colors @alfa33333 and @joshspeagle. The dark mode logo in the sidebar is now a lighter version of Oxford blue (the color @alfa33333 prefers in light mode).

darkmode
lightmode

**Comment by alfa33333** [comment]
I am ok with the  light mode, but I have little preference for the dark mode. Having the same colour gives a more muted tone, but the lighter blue keeps the same vibe as the light mode. So, I leave it to @joshspeagle to decide that part.

**Comment by emprice** [comment]
@alfa33333 You're obviously welcome to mess more with colors, and you can even change them down the road if you want. I just recommend doing so through the Sass partials rather than hardcoding a special case.

**Pull request merged**
